refactor: logging-setup.yaml combine to single script. check all curl return codes.

diff --git a/modules/160-elasticsearch-platform/logging-setup.yaml b/modules/160-elasticsearch-platform/logging-setup.yaml
--- a/modules/160-elasticsearch-platform/logging-setup.yaml
+++ b/modules/160-elasticsearch-platform/logging-setup.yaml
@@ -5,69 +5,82 @@ metadata:
   namespace: platform
 data:
   run: |
-    cp /logging_setup/* /tmp
-    sed -i 's/PW_REPLACE/$ELPASSWORD/' /tmp/kibanausers.sh
-    sed -i 's/PW_REPLACE/$ELPASSWORD/' /tmp/kibana.sh
-    sed -i 's/PW_REPLACE/$ELPASSWORD/' /tmp/elastic.sh
-    /bin/sh /tmp/kibanausers.sh
-    /bin/sh /tmp/kibana.sh
-    /bin/sh /tmp/elastic.sh
+    cp /logging_setup/setup.sh /tmp/
+    sed -i 's/PW_REPLACE/$ELPASSWORD/' /tmp/setup.sh
+    /bin/sh -e /tmp/setup.sh
 
-  kibanausers.sh: |
-    curl -u elastic:PW_REPLACE -XPOST http://logsearch-es-http.platform.svc:9200/_security/role/CP_ROLE -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
+  setup.sh: |
+    CURL='curl -s -w HTTP_CODE%{http_code}'
+    TMP=`mktemp`
+
+    check_curl() {
+      if ! egrep -q "HTTP_CODE$1" $TMP
+      then
+        echo "request failed"
+        cat $TMP
+        rm -f $TMP
+        exit 1
+      fi
+    }
+    $CURL -u elastic:PW_REPLACE -XPOST http://logsearch-es-http.platform.svc:9200/_security/role/CP_ROLE -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
     {
         "cluster":[],
         "indices":[{"names":["*"],"privileges":["read","read_cross_cluster"],
         "allow_restricted_indices":false}],
         "applications":[{"application":"kibana-.kibana","privileges":["feature_discover.all","feature_visualize.all","feature_dashboard.all"],"resources":["*"]}],
         "run_as":[],"metadata":{},"transient_metadata":{"enabled":true}
-    }'
-    curl -u elastic:PW_REPLACE -XPOST http://logsearch-es-http.platform.svc:9200/_security/user/readonly -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
+    }' > $TMP
+    check_curl 200
+    $CURL -u elastic:PW_REPLACE -XPOST http://logsearch-es-http.platform.svc:9200/_security/user/readonly -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
     {
       "password" : "kibana",
       "roles" : [ "CP_ROLE" ]
-    }'
+    }' > $TMP
+    check_curl 200
 
-  kibana.sh: |
-    curl -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/application* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
+    $CURL -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/application* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
     {
       "attributes": {
             "title": "application*",
             "timeFieldName": "@timestamp"
       }
-    }'
-    curl -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/platform* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
+    }' > $TMP
+    check_curl 200
+    $CURL -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/platform* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
     {
       "attributes": {
             "title": "platform*",
             "timeFieldName": "@timestamp"
       }
-    }'
-    curl -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/audit-* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
+    }' > $TMP
+    check_curl 200
+    $CURL -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/audit-* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
     {
       "attributes": {
             "title": "audit*",
             "timeFieldName": "@timestamp"
       }
-    }'
-    curl -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/undecided* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
+    }' > $TMP
+    check_curl 200
+    $CURL -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/undecided* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
     {
       "attributes": {
             "title": "undecided*",
             "timeFieldName": "@timestamp"
       }
-    }'
-    curl -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/ingress* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
+    }' > $TMP
+    check_curl 200
+    $CURL -u elastic:PW_REPLACE -XPOST http://kibana-kb-http.platform.svc:5601/api/saved_objects/index-pattern/ingress* -H "Content-Type: application/json" -H "kbn-xsrf: true" -d'
     {
       "attributes": {
             "title": "ingress*",
             "timeFieldName": "@timestamp"
       }
-    }'
+    }' > $TMP
+    check_curl 200
 
-  elastic.sh: |
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_template/application_template <<EOF
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_template/application_template <<EOF > $TMP
     {
       "index_patterns": ["application*"],
       "order": -1,
@@ -78,8 +91,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_template/platform_template <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_template/platform_template <<EOF > $TMP
     {
       "index_patterns": ["platform*"],
       "order": -1,
@@ -90,8 +104,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_template/audit_template <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_template/audit_template <<EOF > $TMP
     {
       "index_patterns": ["audit*"],
       "order": -1,
@@ -102,8 +117,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_template/ingress_template <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_template/ingress_template <<EOF > $TMP
     {
       "index_patterns": ["ingress*"],
       "order": -1,
@@ -114,8 +130,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_template/undecided_template <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_template/undecided_template <<EOF > $TMP
     {
       "index_patterns": ["undecided*"],
       "order": -1,
@@ -125,8 +142,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_ilm/policy/application_policy <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_ilm/policy/application_policy <<EOF > $TMP
     {
       "policy": {
         "phases": {
@@ -147,8 +165,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_ilm/policy/platform_policy <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_ilm/policy/platform_policy <<EOF > $TMP
     {
       "policy": {
         "phases": {
@@ -169,8 +188,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_ilm/policy/ingress_policy <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_ilm/policy/ingress_policy <<EOF > $TMP
     {
       "policy": {
         "phases": {
@@ -191,8 +211,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_ilm/policy/audit_policy <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_ilm/policy/audit_policy <<EOF > $TMP
     {
       "policy": {
         "phases": {
@@ -213,8 +234,9 @@ data:
       }
     }
     EOF
-    curl -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
-        http://logsearch-es-http.platform.svc:9200/_ilm/policy/undecided_policy <<EOF
+    check_curl '200|409'
+    $CURL -u elastic:PW_REPLACE -XPUT -H"Content-Type: application/json" --data @- \
+        http://logsearch-es-http.platform.svc:9200/_ilm/policy/undecided_policy <<EOF > $TMP
     {
       "policy": {
         "phases": {
@@ -235,6 +257,7 @@ data:
       }
     }
     EOF
+    check_curl '200|409'
 
 ---
 apiVersion: v1
